site_name: 中学生学编程

nav:
  - Home: index.md
  - 前言: 介绍.md
  - 第一章 环境搭建:
      - 什么是操作系统: 第1章/1.1 什么是操作系统.md
      - 如何搭建环境: 第1章/1.2 如何搭建Python.md
      - 为什么学Python: 第1章/1.3 为什么学Python.md
  - 第二章 基础:
      - 开始编程: 第2章/2.1 开始编程.md
      - 基础数据: 第2章/2.2 基础数据.md
      - 变量是什么: 第2章/2.3 变量.md
      - 创建程序:  第2章/2.4 创建程序.md
  - 第三章 逻辑:
      - 判断正数: 第3章/3.1 判断是否正数.md
      - 计算方程: 第3章/3.2 计算方程.md
      - 从1加到100: 第3章/3.3 从1加到100
      - 数学函数的介绍: 第3章/3.4 数学函数的介绍.md
      - 复数的计算: 第3章/3.5 复数的计算.md
      - 猜数字游戏: 第3章/3.6 猜数字游戏.md
  - 第四章 函数:
      - 函数的初步: 第4章/4.1 函数初步.md
      - 计算闰年: 第4章/4.2 计算闰年.md
      - 计算圆周率: 第4章/4.3 计算圆周率.md
      - 手动实现四则运算: 第4章/4.4 手动实现四则运算.md
      - 生成四则运算题: 第4章/4.5 生成四则运算题.md
      - 斐波拉契数列: 第4章/4.6 斐波拉契数列.md
      - 小试数列: 第4章/4.7 小试数列.md
  - 第五章 包管理:
      - 包的导入与使用: 第5章/5.1 包的导入.md
      - 自定义包: 第5章/5.2 自定义包.md
      - 如何寻求帮助: 第5章/5.3 如何寻求帮助.md
      - 安装第三方模块: 第5章/5.4 安装第三方模块.md
  - 第六章 可视化:
      - 函数图像: 第6章/6.1 画函数图像.md
  - about: 关于作者.md

theme: readthedocs
