site_name: 中学生编程

nav:
  - Home: index.md
  - 前言: 介绍.md
  - 第一章 环境搭建:
      - 什么是操作系统: 第1章/1.1 什么是操作系统.md
      - 如何搭建环境: 第1章/1.2 如何搭建Python.md
  - 第二章 基础:
      - 开始编程: 第2章/2.1 开始编程.md
      - 基础数据: 第2章/2.2 基础数据.md
      - 变量是什么: 第2章/2.3 变量.md
  - about: 关于作者.md

theme: readthedocs
