site_name: 中学生编程

nav:
#  - Home: index.md
  - 前言: 介绍.md
  - 第一章 环境搭建: 第1章/如何搭建Python.md
  - 第二章 基础:
      - Hello World: 第2章/如何搭建Python.md
      - 数据类型: 第2章/如何搭建Python.md
  - about: aboutme.md

theme: readthedocs
